name: CI & DevSecOps Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  quality-and-security:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installation des dépendances
        run: |
          npm install
          cd backend && npm install
          cd ../frontend && npm install

      - name: Contrôle anti-triche sur les tests
        run: bash scripts/check-no-cheat.sh

      - name: Construction de l'image Sandbox
        run: docker build -t codearena-sandbox:latest ./sandbox

      - name: Scan de vulnérabilités Trivy (Sandbox)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'codearena-sandbox:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL'
